#!/usr/bin/env bash

# Check array of samples with dasgoclient

samples=()
samples+=(/TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3-PUSummer16v3Fast*/MINIAODSIM)
samples+=(/DYJetsToLL_M-5to50_HT-70to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-5to50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-5to50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-5to50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-5to50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-70to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-600to800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-800to1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-1200to2500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/DYJetsToLL_M-50_HT-2500toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-70To100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-600To800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-800To1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-1200To2500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WJetsToLNu_HT-2500ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)
samples+=(/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv3*/MINIAODSIM)

for sample in "${samples[@]}"; do

    #echo dasgoclient --query="dataset=${sample}"

    # Query DAS and store result in variable for further processing
    result=$(dasgoclient --query="dataset=${sample}")

    # If result is empty, throw error
    if [ -z "${result}" ]; then
        echo "The following sample yields no results:" 2>&1
        echo "${sample}" 2>&1
    fi

    # If result is not unique, throw error
    # We check that the result variable has exactly one line/sample, which
    # simply means, it's unique
    #if [ $(wc -l <<< "${result}") -ne 1 ]; then
    # If it has multiple lines, and the additional samples are just extensions,
    # then the result is still unique
    if [ $(wc -l <<< $(sed 's/_ext[0-9]//' <<< "${result}") | uniq) -ne 1 ]; then

        echo "The following sample is not unique:" 2>&1
        echo "${sample}" 2>&1
        echo "It yields the following results:" 2>&1
        echo "${result}" 2>&1
        exit 1
    fi

    # Print result
    echo "${result}"

done

# No errors, we made it!
echo "Bye."
